"""
Generates the rodent-catch PATTERN the assistant uses when it pre-fills the
Daily Pest Control Monitoring Record (F/HR/17), and writes it as a TypeScript
seed module the app imports:

    python tools/rodent_pattern.py   ->  frontend/src/data/seed/rodentPattern.ts

Why a pattern at all: a register that says "no rodents" every single day tells
an auditor nothing. Real plants see occasional catches, clustered in the wet
months, at a handful of locations. The app applies THIS pattern day by day
(deterministically per calendar date, see frontend/src/engine/rodentPattern.ts)
so that "how many rodents were found, where, over these days / months" has a
sensible answer in Reports > Rodent Trend and in each day's record — with the
location and the number of rodents recorded whenever one is found.

Calibration: the company's own "Rodent Catch Report and Trend Analysis"
(source-documents/Kapila mam department reports .pdf, page 1) reports 0
rodents in 2024, 2 in 2025 (one in May, one in June) and 0 for Jan-Jun 2026 —
i.e. a low, monsoon-leaning incidence. The generated pattern keeps that
seasonal shape but is deliberately a little richer (roughly 8-12 catch days a
year) so the trend is visible in a demo year; the reported history is
embedded verbatim so the report can show both side by side.

Only the Python standard library and numpy are used. Deterministic (fixed
seeds) so re-running it is a no-op unless the inputs below change.
"""
from __future__ import annotations

import json
import random
from pathlib import Path

import numpy as np

OUT = Path(__file__).resolve().parent.parent / "frontend" / "src" / "data" / "seed" / "rodentPattern.ts"

# ---- Seasonal incidence: probability that a given calendar day has a rodent
# catch. A smooth annual curve peaking in the monsoon (Jul-Sep for Mehsana,
# Gujarat), lowest in the dry winter, scaled to ~10 catch days / year.
MONTH_NAMES = ["JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"]
months = np.arange(12)
seasonal = 1.0 + 0.9 * np.cos((months - 7) * 2 * np.pi / 12)  # peak at index 7 = August
TARGET_CATCH_DAYS_PER_YEAR = 10.0
daily_rate = seasonal / seasonal.sum() * TARGET_CATCH_DAYS_PER_YEAR / 30.4
daily_rate = np.round(daily_rate, 4)

# ---- Where rodents turn up: the 16 areas of the Rodent Control Service
# report (verbatim, see masterData.ts), weighted towards food / inward-goods /
# storage areas. Each area owns a block of the 100 numbered trap boxes the
# register says are provided (checkpoint 4 = 100 on the specimen).
AREAS = [
    ("Printing machine - Ground Floor", 0.5),
    ("Anilox cleaning area - Ground floor", 0.4),
    ("Store - Label stock & PVC / PET Films - Ground floor", 1.4),
    ("Ink store - Ground floor", 0.5),
    ("RM Inward & FG Dispatch room - Ground floor", 1.8),
    ("Walkways - Ground Floor", 0.9),
    ("First floor - Walkways", 0.5),
    ("First floor - Slitting & Packing", 0.6),
    ("First floor - Offline punching & QC Inspection", 0.5),
    ("First floor - Printing machine", 0.4),
    ("First floor - Ink Kitchen", 0.4),
    ("First floor - Shrink Sleeve production", 0.4),
    ("First floor - Intermediate Store", 0.9),
    ("Change room & Locker room - Ground Floor", 0.7),
    ("QC Lab", 0.3),
    ("Canteen", 2.0),
]
rng = random.Random(20260908)
boxes_per_area = 100 // len(AREAS)  # 6 each, remainder to the last area
locations = []
next_box = 1
for i, (name, w) in enumerate(AREAS):
    count = boxes_per_area if i < len(AREAS) - 1 else 100 - next_box + 1
    weight = round(w * rng.uniform(0.9, 1.1), 3)  # a little jitter so weights aren't suspiciously round
    locations.append({"area": name, "weight": weight, "boxFrom": next_box, "boxTo": next_box + count - 1})
    next_box += count
assert next_box == 101, next_box

# ---- How many rodents on a catch day, and the conditional signs.
COUNT_DIST = [{"count": 1, "p": 0.72}, {"count": 2, "p": 0.22}, {"count": 3, "p": 0.06}]
SECOND_LOCATION_P = 0.15   # a second area catches on the same day
CAKE_BITING_P = 0.35       # bait-cake biting seen in the box on a catch day (checkpoint 9)
CAKE_BITING_ALONE_P = 0.012  # biting sign on a day with no catch
DEAD_RODENT_P = 0.20       # dead rodent observed on a catch day (checkpoint 8)

# ---- The company's own reported history, transcribed from the PDF page.
HISTORY = [
    {"year": 2024, "months": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], "total": 0},
    {"year": 2025, "months": [0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0], "total": 2},
    {"year": 2026, "months": [0, 0, 0, 0, 0, 0, None, None, None, None, None, None], "total": None},
]

ts = f"""// GENERATED by tools/rodent_pattern.py — do not edit by hand; edit the
// Python and re-run it. See that file for how each number was derived and
// how the pattern was calibrated against the company's own Rodent Catch
// Report (0 rodents in 2024, 2 in 2025, 0 through Jun-2026).

// Probability that a given calendar day has a rodent catch, by month
// (Jan..Dec). Seasonal — peaks in the monsoon, ~{TARGET_CATCH_DAYS_PER_YEAR:.0f} catch days a year.
export const RODENT_MONTHLY_RATE: number[] = {json.dumps([float(x) for x in daily_rate])};

// The 16 Rodent Control Service areas with catch weights and the numbered
// trap boxes (RB-01..RB-100) each one owns.
export interface RodentLocationSpec {{
  area: string;
  weight: number;
  boxFrom: number;
  boxTo: number;
}}
export const RODENT_LOCATIONS: RodentLocationSpec[] = {json.dumps(locations, indent=2)};

// Rodents per catch day.
export const RODENT_COUNT_DIST: {{ count: number; p: number }}[] = {json.dumps(COUNT_DIST)};
export const RODENT_SECOND_LOCATION_P = {SECOND_LOCATION_P};
export const RODENT_CAKE_BITING_P = {CAKE_BITING_P};
export const RODENT_CAKE_BITING_ALONE_P = {CAKE_BITING_ALONE_P};
export const RODENT_DEAD_P = {DEAD_RODENT_P};

// The company's own "Rodent Catch Report and Trend Analysis" — Source:
// Trapped on Glue boards in Roda-boxes; Unit: Number; Target Pest: Rodents.
// null = month not yet reported on the source page.
export interface RodentHistoryRow {{
  year: number;
  months: (number | null)[];
  total: number | null;
}}
export const RODENT_HISTORY_REPORTED: RodentHistoryRow[] = {json.dumps(HISTORY, indent=2)};
export const RODENT_HISTORY_SOURCE = "Kapila mam department reports .pdf, page 1 — Rodent Catch Report and Trend Analysis";
export const RODENT_REPORT_MONTHS = {json.dumps(MONTH_NAMES)};
"""

OUT.write_text(ts, encoding="utf-8", newline="\n")
print(f"wrote {OUT}")
print("daily rate by month:", dict(zip(MONTH_NAMES, [float(x) for x in daily_rate])))
print("expected catch days / year:", round(float((daily_rate * 30.4).sum()), 1))
